"""Report generation: the deliverable that actually matters.

The PDF is what an adjuster reads. It has to be honest about what is an
estimate versus what the owner verified, it has to be itemised by room, and it
has to carry photographs — because a list of numbers without pictures gets
argued down.
"""

from __future__ import annotations

import csv
import io
import os
import zipfile
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    Image as RLImage,
    KeepTogether,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from . import media, values

INK = colors.HexColor("#1b1b1f")
MUTED = colors.HexColor("#6b6b76")
RULE = colors.HexColor("#d8d8de")
ACCENT = colors.HexColor("#b3401f")
BAND = colors.HexColor("#f4f1ec")


def _styles():
    ss = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=ss["Title"], fontName="Helvetica-Bold",
                                fontSize=26, leading=30, textColor=INK, alignment=TA_LEFT,
                                spaceAfter=4),
        "sub": ParagraphStyle("s", parent=ss["Normal"], fontName="Helvetica",
                              fontSize=11, leading=15, textColor=MUTED, spaceAfter=2),
        "h2": ParagraphStyle("h2", parent=ss["Heading2"], fontName="Helvetica-Bold",
                             fontSize=14, leading=18, textColor=INK,
                             spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("b", parent=ss["Normal"], fontName="Helvetica",
                               fontSize=9.5, leading=13.5, textColor=INK),
        "small": ParagraphStyle("sm", parent=ss["Normal"], fontName="Helvetica",
                                fontSize=8, leading=11, textColor=MUTED),
        "cell": ParagraphStyle("c", parent=ss["Normal"], fontName="Helvetica",
                               fontSize=8, leading=10.5, textColor=INK),
        "cellb": ParagraphStyle("cb", parent=ss["Normal"], fontName="Helvetica-Bold",
                                fontSize=8, leading=10.5, textColor=INK),
        "statn": ParagraphStyle("stn", parent=ss["Normal"], fontName="Helvetica-Bold",
                                fontSize=17, leading=20, textColor=INK, alignment=TA_CENTER),
        "statl": ParagraphStyle("stl", parent=ss["Normal"], fontName="Helvetica",
                                fontSize=7.5, leading=10, textColor=MUTED, alignment=TA_CENTER),
        "cap": ParagraphStyle("cap", parent=ss["Normal"], fontName="Helvetica",
                              fontSize=7.5, leading=9.5, textColor=MUTED, alignment=TA_CENTER),
    }


class _Report(BaseDocTemplate):
    """Doc template that stamps a footer with page numbers and a source line."""

    def __init__(self, buf, title, **kw):
        super().__init__(buf, pagesize=LETTER, title=title, author="EmberProof",
                         leftMargin=0.7 * inch, rightMargin=0.7 * inch,
                         topMargin=0.7 * inch, bottomMargin=0.75 * inch, **kw)
        frame = Frame(self.leftMargin, self.bottomMargin, self.width, self.height, id="f")
        self.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=self._footer)])

    def _footer(self, canvas, doc):
        canvas.saveState()
        y = 0.5 * inch
        canvas.setStrokeColor(RULE)
        canvas.setLineWidth(0.5)
        canvas.line(doc.leftMargin, y + 12, doc.leftMargin + doc.width, y + 12)
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(MUTED)
        canvas.drawString(doc.leftMargin, y, "Generated by EmberProof — local-first home inventory")
        canvas.drawRightString(doc.leftMargin + doc.width, y, f"Page {doc.page}")
        canvas.restoreState()


def _money(cents) -> str:
    if cents is None:
        return "—"
    return f"${cents / 100:,.0f}"


def build_property_pdf(path: str, prop: dict, rooms: list[dict], items: list[dict],
                       photos_by_item: dict[int, list[dict]], media_root: str) -> str:
    """Render the claim report. `items` are flat rows; `rooms` carry item ids."""
    S = _styles()
    buf = io.BytesIO()
    doc = _Report(buf, title=f"Contents inventory — {prop['name']}")

    verified = [i for i in items if i["value_source"] in ("manual", "receipt")]
    estimated = [i for i in items if i["value_source"] == "estimate"]
    total = sum((i["replacement_value_cents"] or 0) for i in items)
    total_verified = sum((i["replacement_value_cents"] or 0) for i in verified)
    photo_count = sum(len(v) for v in photos_by_item.values())
    generated = datetime.now(timezone.utc).strftime("%B %d, %Y")

    story: list = []

    # ---- cover -------------------------------------------------------------
    story.append(Paragraph("Home contents inventory", S["title"]))
    story.append(Paragraph(prop["name"], S["sub"]))
    if prop.get("address"):
        story.append(Paragraph(prop["address"], S["sub"]))
    meta_bits = [f"Prepared {generated}"]
    if prop.get("insurer"):
        meta_bits.append(f"Insurer: {prop['insurer']}")
    if prop.get("policy_number"):
        meta_bits.append(f"Policy: {prop['policy_number']}")
    story.append(Paragraph(" &nbsp;·&nbsp; ".join(meta_bits), S["small"]))
    story.append(Spacer(1, 16))

    stats = [
        (str(len(items)), "items documented"),
        (str(len(rooms)), "rooms"),
        (_money(total), "total replacement value"),
        (str(photo_count), "photographs"),
    ]
    cells = [[Paragraph(n, S["statn"]) for n, _ in stats],
             [Paragraph(l, S["statl"]) for _, l in stats]]
    t = Table(cells, colWidths=[doc.width / 4.0] * 4)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BAND),
        ("BOX", (0, 0), (-1, -1), 0.5, RULE),
        ("TOPPADDING", (0, 0), (-1, 0), 12),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 12),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t)
    story.append(Spacer(1, 18))

    if estimated:
        story.append(Paragraph(
            f"<b>How to read the values.</b> {len(verified)} of {len(items)} items carry a "
            f"value you confirmed ({_money(total_verified)}). The remaining {len(estimated)} "
            "carry a category estimate, marked <b>est.</b> in the tables below. Estimates are "
            "a floor to argue from, not a valuation — attach receipts or appraisals for "
            "anything you would contest.", S["body"]))
        story.append(Spacer(1, 10))

    story.append(Paragraph(
        "This document was assembled by the property owner from their own photographs and "
        "records. Item values reflect replacement cost at the time of writing. Original "
        "photographs and receipts are retained alongside this report.", S["small"]))

    # ---- per-room item tables ---------------------------------------------
    by_room: dict[int, list[dict]] = {}
    for it in items:
        by_room.setdefault(it["room_id"], []).append(it)

    for room in rooms:
        rows = by_room.get(room["id"], [])
        if not rows:
            continue
        room_total = sum((r["replacement_value_cents"] or 0) for r in rows)
        story.append(PageBreak())
        story.append(Paragraph(
            f"{room['name']} <font size=10 color='#6b6b76'>— {len(rows)} items, "
            f"{_money(room_total)}</font>", S["h2"]))

        head = ["Item", "Cat.", "Qty", "Brand / model / serial", "Value", "Src"]
        data = [[Paragraph(f"<b>{h}</b>", S["cell"]) for h in head]]
        for r in rows:
            ident = " / ".join(x for x in [r["brand"], r["model"]] if x) or "—"
            if r["serial"]:
                ident += f"<br/><font size=7 color='#6b6b76'>SN {r['serial']}</font>"
            desc = r["name"]
            if r["description"]:
                desc += f"<br/><font size=7 color='#6b6b76'>{r['description'][:120]}</font>"
            src = "est." if r["value_source"] == "estimate" else "ver."
            data.append([
                Paragraph(desc, S["cell"]),
                Paragraph(values.label(r["category"]), S["cell"]),
                Paragraph(str(r["quantity"]), S["cell"]),
                Paragraph(ident, S["cell"]),
                Paragraph(_money(r["replacement_value_cents"]), S["cell"]),
                Paragraph(src, S["cell"]),
            ])

        widths = [doc.width * w for w in (0.34, 0.13, 0.06, 0.27, 0.12, 0.08)]
        tbl = Table(data, colWidths=widths, repeatRows=1)
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BAND),
            ("LINEBELOW", (0, 0), (-1, 0), 0.7, INK),
            ("LINEBELOW", (0, 1), (-1, -1), 0.25, RULE),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 3),
            ("RIGHTPADDING", (0, 0), (-1, -1), 3),
            ("ALIGN", (2, 0), (2, -1), "CENTER"),
            ("ALIGN", (4, 0), (4, -1), "RIGHT"),
            ("ALIGN", (5, 0), (5, -1), "CENTER"),
        ]))
        story.append(tbl)

    # ---- photo appendix ----------------------------------------------------
    photo_items = [i for i in items if photos_by_item.get(i["id"])]
    if photo_items:
        story.append(PageBreak())
        story.append(Paragraph("Photographic record", S["h2"]))
        story.append(Paragraph(
            "One representative photograph per item. Full-resolution originals are kept "
            "with the inventory.", S["small"]))
        story.append(Spacer(1, 10))

        cell_w = (doc.width - 2 * 12) / 3.0
        grid, row = [], []
        for it in photo_items:
            ph = photos_by_item[it["id"]][0]
            src = os.path.join(media_root, "originals", ph["filename"])
            jpg = media.to_pdf_jpeg(src, max_size=(700, 700))
            if jpg is None:
                cell = Paragraph(f"<font size=7>{it['name']}</font>", S["cap"])
            else:
                ir = ImageReader(io.BytesIO(jpg))
                iw, ih = ir.getSize()
                scale = min((cell_w - 8) / iw, 1.05 * inch / ih)
                cell = RLImage(io.BytesIO(jpg), width=iw * scale, height=ih * scale)
            row.append([cell, Paragraph(it["name"][:60], S["cap"])])
            if len(row) == 3:
                grid.append(row)
                row = []
        if row:
            while len(row) < 3:
                row.append(["", ""])
            grid.append(row)

        flat = []
        for r in grid:
            flat.append([c[0] for c in r])
            flat.append([c[1] for c in r])
        gt = Table(flat, colWidths=[cell_w + 12] * 3, rowHeights=None)
        gt.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(gt)

    doc.build(story)
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(buf.getvalue())
    return path


def build_csv(path: str, prop: dict, items: list[dict], photos_by_item: dict) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    cols = ["room", "item", "category", "description", "brand", "model", "serial",
            "quantity", "purchase_date", "purchase_price_usd", "replacement_value_usd",
            "value_source", "photos", "notes"]
    with open(path, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["property", prop["name"]])
        if prop.get("address"):
            w.writerow(["address", prop["address"]])
        w.writerow([])
        w.writerow(cols)
        for i in items:
            w.writerow([
                i["room_name"], i["name"], values.label(i["category"]), i["description"] or "",
                i["brand"] or "", i["model"] or "", i["serial"] or "", i["quantity"],
                i["purchase_date"] or "",
                f"{(i['purchase_price_cents'] or 0) / 100:.2f}" if i["purchase_price_cents"] else "",
                f"{(i['replacement_value_cents'] or 0) / 100:.2f}" if i["replacement_value_cents"] is not None else "",
                i["value_source"], len(photos_by_item.get(i["id"], [])), i["notes"] or "",
            ])
    return path


def build_backup(path: str, db_path: str, media_root: str, manifest: dict) -> str:
    """Zip a consistent database snapshot, every stored file, and a manifest.

    Delegates to backup.build_archive, which snapshots with VACUUM INTO. A plain
    copy of the .db file would miss anything still sitting in the WAL — the exact
    failure you cannot afford in a disaster-recovery tool.
    """
    from . import backup

    return backup.build_archive(path, db_path, media_root, manifest)